### ISSUE TITLE
Bump document model version to 133

### ISSUE THREAD

**Issue by jpedroso** [sketch-hq/sketch-file-format#104]
Migrating document color presets to color variables requires a new document model migration and thus a new version. See issue [#29375](https://github.com/sketch-hq/Sketch/issues/29375).

This version is declared as `MSDocumentCopyColorAssetsToSwatches = 133` in `MSDocumentVersion.h`.

**Comment by jedrichards** [comment]
@jpedroso Ah, so literally just a bump, no other changes?

**Comment by jpedroso** [comment]
Yes, no other changes. The migration just creates a new swatch color for each of the document color presets and adds it to the document.

**Comment by jedrichards** [comment]
@jpedroso Ok that has been released as version `3.6.4`. So to stop Jenkins complaining you can update Sketch by following [the instructions](https://www.notion.so/sketchapp/Sketch-File-Format-Specification-4e2e66dff2164af6b8d52fe09ae434a0#8991717f781042faaf43293412069d4e) 😃
