### ISSUE TITLE
No more `changeIdentifier` for symbol masters in version 134?

### ISSUE THREAD

**Issue by rodionovd** [sketch-hq/sketch-file-format#116]
Hi there,

We noticed that Sketch 69 doesn't reference this property anywhere and it's being removed from older documents when you save them with 69 — but the [spec](https://github.com/sketch-hq/sketch-file-format/blob/3ac1dc2693d7b61982a5a23e471973088f9d11b3/schema/layers/symbol-master.schema.yaml) still mentions it. Wondering if that's just an oversight or something.

Thanks!

**Comment by jedrichards** [comment]
Hmm yes, thanks for the report - it looks like Sketch 69 and the file-format have got slightly out of sync. I'll look into it - but expect an update to the file format fairly soon to remove `changeIdentifier` from the spec.

**Comment by rodionovd** [comment]
Awesome, thank you!

**Comment by christianklotz** [comment]
**For engineering**

Drop the following line:

https://github.com/sketch-hq/sketch-file-format/blob/3ac1dc2693d7b61982a5a23e471973088f9d11b3/schema/layers/symbol-master.schema.yaml#L21

… and ensure the `version` attribute is updated accordingly to reflect outcome of https://github.com/sketch-hq/Sketch/issues/31795:

https://github.com/sketch-hq/sketch-file-format/blob/eeabd7caeefd55bcb52c93ec50097b2ae63cea7b/schema/meta.schema.yaml#L25-L41

**Comment by jedrichards** [comment]
Based on https://github.com/sketch-hq/Sketch/issues/31795 it sounds like we won't be updating the version attribute, and instead just silently dropping `changeIdentifier`. That change should be released as a new patch version of the file format.
