### ISSUE TITLE
Finalise guide for working on the file format

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-file-format#12]
Notes from Notion:

- Goal is to communicate clearly that it's not us dictating changes on the file format but this is the place for everyone making changes on the file persistence layer to define and document them.
- Is it possible to provide a sample scenarios for (non-)breaking change?
- Make clear this is going first and foremost about helping robust products across our organisation

**Comment by christianklotz** [comment]
Closing for now, we see how things go with the next few changes being introduced to the file format and revisit if necessary.
