### ISSUE TITLE
How to parse CurvePoint to SVG Path

### ISSUE THREAD

**Issue by noahlam** [sketch-hq/sketch-file-format#144]
How to parse CurvePoint to SVG Path?

I am working for parse sketch rectangle to a svg file recently.   And I spend a lot of time to parse CurvePoint within points, But I still can't parse it correctly.

Could any one tell me how to parse it, thanks!

**Comment by christianklotz** [comment]
SVG conversion is a separate issue, not strictly related to the file format schema. For this reason I'm closing this issue.

However, please follow https://www.sketch.com/blog/ in the coming weeks as we are preparing more info on this 🙂

**Comment by bplok20010** [comment]
> How to parse CurvePoint to SVG Path?
> 
> I am working for parse sketch rectangle to a svg file recently. And I spend a lot of time to parse CurvePoint within points, But I still can't parse it correctly.
> 
> Could any one tell me how to parse it, thanks!

@noahlam I have the same problem. Have you solved it?
