### ISSUE TITLE
Optional alignment in ParagraphStyle

### ISSUE THREAD

**Issue by raveclassic** [sketch-hq/sketch-file-format#31]
Looks like `alignment` property in `ParagraphStyle` schema should also be added to `optional` list: https://github.com/sketch-hq/sketch-file-format/blob/d61c8a2e3d81ecfe0890d39e1a48f2add77801cb/schema/objects/paragraph-style.schema.yaml#L4-L9

It's missing in some of the `TextStyle`s generated for 121 file format.

**Comment by jedrichards** [comment]
👍
