### ISSUE TITLE
ColorControls property units

### ISSUE THREAD

**Issue by raveclassic** [sketch-hq/sketch-file-format#32]
Looks like `ColorControls` schema defines invalid 0-1 float units for its properties: https://github.com/sketch-hq/sketch-file-format/blob/d61c8a2e3d81ecfe0890d39e1a48f2add77801cb/schema/objects/color-controls.schema.yaml#L7-L10

However the values vary from -100% to 100%:
![image](https://user-images.githubusercontent.com/1743568/69158338-5061ad80-0af7-11ea-96fc-f9b62e06b3a0.png)

**Comment by jedrichards** [comment]
Another good catch, will address this and the others in an upcoming patch fix.
