### ISSUE TITLE
Unnecessary sharedStyleID in shape-group.schema

### ISSUE THREAD

**Issue by omaralbeik** [sketch-hq/sketch-file-format#50]
In [shape-group.schema](https://github.com/sketch-hq/sketch-file-format/blob/v3.3.0/schema/layers/shape-group.schema.yaml), the `sharedStyleID` property is already included in [`abstract-group.schema`](https://github.com/sketch-hq/sketch-file-format/blob/v3.3.0/schema/layers/abstract-group.schema.yaml)

**Comment by jedrichards** [comment]
Ah yes. Thanks! 🙂
