### ISSUE TITLE
No value for key `frame` in `page`

### ISSUE THREAD

**Issue by omaralbeik** [sketch-hq/sketch-file-format#51]
The specs for [page](https://github.com/sketch-hq/sketch-file-format/blob/master/schema/layers/page.schema.yaml) specifies inheritance from abstract-layer which has a required `frame` property
I can't find the key `frame` in a page saved by Sketch v61.2

**Comment by jedrichards** [comment]
Yep I think you're right. I should look into any other differences between pages and layers, could be it isn't appropriate for page to inherit from groups/layers and should just be defined as it own thing, despite some duplication of properties.

**Comment by jedrichards** [comment]
Hmm I'm not sure about this one. Are you sure you can't find `frame` in page objects? We have this repo of Sketch file JSON that gets automatically generated and saved in the repo. As you can see there are `frame` props on pages:

https://github.com/sketch-hq/sketch-reference-files/blob/master/files/123/empty/pages/508625BF-279B-4BC1-8DED-38B0FC1880E0.json#L24-L31

**Comment by omaralbeik** [comment]
Apologies for the late response,
I'm not sure now, I can't reproduce the error, will close this issue for now
Thanks!
