### ISSUE TITLE
Smart layout axis not work

### ISSUE THREAD

**Issue by YCaptain** [sketch-hq/sketch-file-format#77]
The `inferred-layout-axis.schema.yaml` schema is not working as what I saw after unzipped a sketch file where integer 0 represents `Horizontal` and 1 represents `Vertical`.

Where
```
enum:
  - 0
  - 1
  - 2
enumDescriptions:
  - None
  - Horizontal
  - Vertical
```

Should be
```
enum:
  - 0
  - 1
enumDescriptions:
  - Horizontal
  - Vertical
```

**Comment by YCaptain** [comment]
It seems the group layout value could be `"groupLayout": { "_class": "MSImmutableFreeformGroupLayout" }` if it is not set inferred layout.

**Comment by jedrichards** [comment]
> It seems the group layout value could be "groupLayout": { "_class": "MSImmutableFreeformGroupLayout" } if it is not set inferred layout.

Yep you're correct. Without an inferred (smart) layout set the groupLayout value is a `MSImmutableFreeformGroupLayout`.
